manifest:
  remotes:
    - name: aaroncorgan
      url-base: https://github.com/aaroncorgan
  projects:
    - name: zmk
      remote: aaroncorgan
      revision: main
      import: app/west.yml
  self:
    path: config
